@startuml クラス図

class Users {
    - user_id: String
    - user_name: String
    - full_name: String
    - phone_number: String
    - email_address: String
    - password: String
    - age: Integer
    - gender: String
    - current_event_id: String
    - current_group_id: String
    - user_status: String
}

class Admins {
    - user_id: String
    - user_name: String
    - password: String
    - full_name: String
    - email_address: String
}

class Companies {
    - company_id: String
    - company_name: String
    - company_password: String
    - address: String
    - phone_number: String
    - email_address: String
}

class CompaniesEmployee {
    - company_id: String
    - user_id: String
    - user_name: String
    - full_name: String
    - password: String
    - email_address: String
}

class Groups {
    - group_id: String
    - password: String
    - user_id: String
    - creation_date: DateTime
    - max_members: Integer
    - current_members: Integer
    - event_id: String
}

class Events {
    - company_id: String
    - event_name: String
    - event_id: String
    - password: String
    - start_time: DateTime
    - end_time: DateTime
    - location: String
    - event_content: Text
}

class Messages {
    - message_id: String
    - sender_user_id: String
    - reciver_user_id: String
    - message_content: Text
    - sent_time: DateTime
}

class LocationData {
    - user_id: String
    - user_stats: String
    - current_latitude: Float
    - current_longitude: Float
    - acquisition_time: DateTime
}

class LocationHistory {
    - user_id: String
    - latitude: Float
    - longitude: Float
    - acquisition_time: DateTime
    - user_status: String
}


Users "1" -- "0..*" Events : current_event_id
Users "1" -- "0..*" Groups : current_group_id
Users "1" -- "0..*" Messages : sender_user_id
Users "1" -- "0..*" Messages : reciver_user_id
Users "1" -- "0..*" LocationData : user_id
Users "1" -- "0..*" LocationHistory : user_id
Companies "1" -- "0..*" Events : company_id
Companies "1" -- "0..*" CompaniesEmployee : company_id
Groups "1" -- "0..*" Users : user_id
Events "1" -- "0..*" Groups : event_id
@enduml
