@startuml 管理者
left to right direction
actor 管理者

管理者 -- (利用者の登録情報を確認する)
管理者 -- (ツアー情報を登録する)
管理者 -- (ツアー情報の変更する)
管理者 -- (ツアー情報の削除をする)
管理者 -- (グループの作成をする)
管理者 -- (グループの変更をする)
管理者 -- (グループの削除をする)
管理者 -- (利用者の位置情報を取得する)
管理者 -- (利用者の位置情報の間隔を設定する)
管理者 -- (利用者の異常を確認する)
管理者 -- (利用者の情報を削除する)
@enduml