@startuml 管理者
left to right direction
actor 管理者

管理者 -- (利用者の登録情報を確認する)
管理者 -- (ツアー情報を登録)
管理者 -- (ツアー情報の変更)
管理者 -- (ツアー情報の削除)
管理者 -- (グループの作成)
管理者 -- (グループの変更)
管理者 -- (グループの削除)
管理者 -- (利用者の位置情報を取得する)
管理者 -- (利用者の位置情報の間隔を設定する)
管理者 -- (利用者の異常を確認する)
管理者 -- (利用者の情報を削除する)
@enduml