@startuml ユースケース

left to right direction
actor 利用者

利用者 -- (新規登録する)
利用者 -- (登録情報を確認する)
利用者 -- (登録情報を変更する)
利用者 -- (登録情報を削除する)
利用者 -- (グループに参加する)
利用者 -- (グループを退出する)
利用者 -- (自身の状態を変更する)
利用者 -- (緊急通知送信する)
利用者 -- (管理者とチャットする)
利用者 -- (ルートを表示する)
利用者 -- (位置情報を取得する)

@enduml