@startuml user_usecase(2)

left to right direction
actor ユーザー

ユーザー -- (グループを作成する)
ユーザー -- (グループに参加する)
ユーザー -- (グループを退出する)
ユーザー -- (自身の状況を変更する)
ユーザー -- (位置情報を表示する)
ユーザー -- (ルートを表示する)
ユーザー -- (システム管理者とチャットする)



@enduml
