@startuml ユースケース

left to right direction
actor ユーザー

ユーザー -- (ユーザーを新規登録する)
ユーザー -- (ログインをする)
ユーザー -- (ログアウトをする)
ユーザー -- (登録情報を確認する)
ユーザー -- (登録情報を変更する)
ユーザー -- (登録情報を削除する)
ユーザー -- (グループに参加する)
ユーザー -- (グループを退出する)
ユーザー -- (自身の状況を変更する)
ユーザー -- (位置情報を表示する)
ユーザー -- (ルートを表示する)
ユーザー -- (管理者とチャットする)
ユーザー -- (緊急通知を送信する)



(ユーザーを新規登録する) <|-- (名前を入力する)
(ユーザーを新規登録する) <|-- (電話番号を入力する)

(グループに参加する) <|-- (グループ番号を入力する)

@enduml
