@startuml 提案先
left to right direction
actor 提案先

提案先 -- (ツアー参加者の登録情報を確認する)
提案先 -- (提案先が新規登録する)
提案先 -- (提案先がログインする)
提案先 -- (提案先がログアウトする)
提案先 -- (ツアー情報を登録する)
提案先 -- (ツアー情報の変更をする)
提案先 -- (ツアー情報を削除する)
提案先 -- (イベントの作成をする)
提案先 -- (イベントを変更する)
提案先 -- (イベントを削除する)


@enduml