@startuml 管理者
left to right direction
actor 管理者

管理者 -- (管理者がログインする)
管理者 -- (管理者がログアウトする)
管理者 -- (ユーザーの登録情報を確認する)
管理者 -- (ユーザーの異常を確認する)
管理者 -- (ユーザーの情報を削除する)

(ユーザーの異常を確認する) <|-- (ユーザーの位置情報を表示する)
(ユーザーの異常を確認する) <|-- (ユーザーに連絡する)
(ユーザーの異常を確認する) <|-- (救急隊に通報する)


@enduml