@startuml グループ作成シーケンス図
actor ユーザー
boundary "グループ作成画面"
control "グループ情報登録"
entity "グループ"
control "表示"
boundary "グループ画面"
control "エラー画面表示"
boundary "エラー画面"

activate ユーザー
    ユーザー --> グループ作成画面
    activate グループ作成画面
    グループ作成画面 --> グループ情報登録
    activate グループ情報登録
    グループ情報登録 --> 表示
    activate グループ情報登録
    グループ情報登録 --> グループ
    グループ <-- グループ情報登録
    activate グループ
    activate 表示
    表示 --> グループ画面
    activate グループ画面
    エラー画面表示 --> エラー画面
    activate 表示
@enduml