@startuml グループ作成シーケンス図
actor ユーザー as 0
boundary ":グループ作成画面" as a
control ":グループ情報登録" as b
entity ":グループ" as c
control ":表示" as d
boundary ":グループ画面" as e
control ":エラー画面表示" as f
boundary ":エラー画面" as g

activate 0
    0 -> a:1:グループ情報入力()
    deactivate 0
    activate a
    a -> b:1.1:入力情報確認()
    deactivate a
    activate b
    b -> d:1.2:正常終了時()
    activate d
    d -> e:1.2.1表示()
    activate e
    deactivate e
    deactivate d
    b -> f:1.3:型式間違い入力()
    activate f
    f -> g:1.4:表示()
    activate g
    b -> c:1.5:登録
    activate c
    c --> b
    deactivate c
@enduml

@startuml グループ参加シーケンス図
actor ユーザー as 0
boundary ":グループ参加画面" as a
control ":入力内容照合" as b
entity ":グループ" as c
control ":表示" as d
boundary ":グループ画面" as e
control ":エラー画面表示" as f
boundary ":エラー画面" as g

activate 0
    0 -> a:1:グループID、パスワード入力()
    deactivate 0
    activate a
    a -> b:1.2:入力内容確認()
    deactivate a
    activate b
    b -> d:1.3:正常終了時()
    activate d
    d -> e:1.3.1:表示()
    activate e
    deactivate e
    deactivate d
    b -> f:1.4:入力間違い()
    activate f
    f -> g:1.4.1:表示()
    activate g
    b -> c:1.5:照合()
    activate c
    c --> b
    deactivate c 
@enduml

@startuml グループ退出シーケンス図
actor ユーザー as 0
boundary ":グループ確認画面" as a
control ":表示" as b
boundary ":退出ダイアログ" as c
control ":更新" as d
entity ":グループ" as e
control ":表示" as f
boundary ":トップページ" as g
control ":表示" as h
boundary ":退出処理エラー" as i

activate 0
    0 -> a:1:退出をクリック()
    activate a
    a -> b::入力内容確認()
    deactivate a
    activate b
    b -> c:表示()
    deactivate b
    activate c
    0 -> c:1.1:はい/いいえを選択()
    deactivate 0
    c -> a:1.1.1:いいえ選択時()
    activate a
    c -> d
    activate d
    d -> f:1.2:正常終了時()
    activate f
    f -> g:表示()
    activate g
    deactivate f
    deactivate g
    d -> h:1.3:システム不良時()
    activate h
    h -> i:表示()
    activate i
    d -> e:更新()
    activate e
    e --> d
    deactivate d
@enduml

@startuml 状況変更シーケンス図
actor ユーザー as 0
boundary ":マップ画面" as a
control ":ユーザー状況変更" as b
entity ":ユーザー" as c
control ":表示" as d
boundary ":マップ画面" as e
control ":表示" as f
boundary ":情報更新エラー画面" as g

activate 0
    0 -> a:1:自分の状況をクリック()
    deactivate 0
    activate a
    a -> b:変更確認()
    deactivate a
    activate b
    b -> d:1.1:正常終了時()
    activate d
    d -> e:表示()
    activate e
    deactivate e
    deactivate d
    b -> f:1.2:システム不良時()
    activate f
    f -> g:表示()
    activate g
    b -> c:変更()
    activate c
    c --> b
    deactivate c 
@enduml

@startuml ルート表示シーケンス図
actor ユーザー as 0
boundary ":マップ画面" as a
control ":位置情報取得" as b
entity ":位置情報" as c
control ":ルート作成" as d
boundary ":マップ画面" as e
control ":表示" as f
boundary ":ルート更新エラー画面" as g

activate 0
    0 -> a:ルート作成()
    deactivate 0
    activate a
    a -> b:起動()
    deactivate a
    activate b
    b -> d:1.1:正常終了時()
    activate d
    d -> e:表示()
    activate e
    deactivate e
    deactivate d
    b -> f:1.2:システム不良時()
    activate f
    f -> g:表示()
    activate g
    b -> c:位置情報()
    activate c
    c --> b
    deactivate c 
@enduml

@startuml システム管理者チャットシーケンス図
actor ユーザー as 0
boundary ":トップページ" as a
control ":取得" as b
entity ":メッセージ" as c
control ":表示" as d
boundary ":チャット更新エラー画面" as e
boundary ":チャット画面" as f
control ":追加" as g
entity ":メッセージ" as h

activate 0
    0 -> a:1:チャットをクリック()
    deactivate 0
    activate a
    a -> b:1.1:取得()
    deactivate a
    activate b
    b -> c:1.2:表示()
    activate c
    c --> b
    deactivate c
    alt [異常時]
    b -> d:1.3:システム不良時()
    activate d
    d --> b
    d -> e:1.3.1:表示()
    deactivate d
    activate e
    e -[hidden]-> e
    deactivate e
    else [正常時]
    b -> d:1.4:正常終了時()
    
    activate d
    d --> b
    d -> f:1.4.1:表示()
    deactivate b
    activate f
    
    f --> d
    deactivate d
    0 -> f:1.3:メッセージを送信()
    activate 0
    f --> 0
    deactivate 0
    f -> g:1.5:追加()
    activate g
    g --> f
    deactivate f
    g -> h:1.6:追加()
    activate h
    h --> g
    deactivate h
    deactivate g
    end
    

@enduml

@startuml 位置情報表示シーケンス図
actor ユーザー as 0
boundary ":マップ画面" as a
control ":データ取得" as b
entity ":位置情報" as c
control ":表示" as d
boundary ":マップ画面" as e
control ":表示" as f
boundary ":エラー内容ポップアップ" as g
control ":表示" as h
boundary ":マップ画面" as i

activate 0
    0 -> a
    deactivate 0
    activate a
    a -> b
    deactivate a
    activate b
    b -> d:1.1:正常終了時()
    activate d
    d -> e
    activate e
    deactivate e
    deactivate d
    b -> f:1.2:自身の位置情報が取得できない場合()
    activate f
    f -> g:1.2.1:マップ上表示()
    activate g
    deactivate f
    deactivate g
    deactivate d
    b -> h:1.3:グループメンバーの位置情報が取得ができない場合()
    activate h
    h -> i
    activate i
    b -> c
    activate c
    c --> b
    deactivate c 
@enduml
